"""
This type stub file was generated by pyright.
"""

from rest_framework import serializers

class AuthTokenSerializer(serializers.Serializer):
    username = ...
    password = ...
    token = ...
    def validate(self, attrs):
        ...
    


