# Generated by Django 5.2.3 on 2025-08-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="2025-08-28T08:53:07.115509+00:00", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default="2025-08-28T08:54:04.370049+00:00", max_length=200, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productimage",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_adjustment",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "name", "value")},
        ),
    ]
