# Generated by Django 5.2.3 on 2025-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(default='Default Shop', max_length=100),
            preserve_default=False,
        ),
    ]
