# Generated by Django 5.2.3 on 2025-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorbankdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
